added german count
AmoleR/conlin-bot pull request #6
Opened 2021-09-19 20:32 UTC by george-gino

added a random so that it does either guten morgen or count german

2021-09-19 20:35 UTC, AmoleR requested changes
In general, here are a few tips.
- Store random variables in an `ArrayList` so that you can just access it with `array.get(random)`, and adding more is easy.
- Delete extra lines (i.e. line 21).
- Don't use `{ .. }` for one line things, do
```java
if (check == 1)
  sendMessage(...);
else
  sendMessage(...);
```

2021-09-20 02:47 UTC, closed without merging

2021-09-20 02:48 UTC, VincentZhao12 reviewed
please learn java

2021-09-20 02:48 UTC, VincentZhao12 commented on src/main/java/Listener.java
> +        int check = (int)(Math.random() * (4 - 1 + 1) + 1);
-1+1 is pointless

2021-09-20 02:48 UTC, VincentZhao12 commented on src/main/java/Listener.java
> +                foreign(event);
do u know how to write a case for switch case? do u not see the other cases above? can u not copy paste?